participants:

    Calculix:
        interfaces:
        - nodes-mesh: Solid-Mesh
          patch: interface
          write-data: [Displacements]
          read-data: [Forces]

precice-config-file: ../precice-config.xml