participants:

    Calculix:
        interfaces:
        - nodes-mesh: Solid-Nodes
          patch: interface
          write-data: [Displacements]
          read-data: [Forces]

precice-config-file: ../precice-config-interface.xml