participants:

    Calculix:
        interfaces:
        - nodes-mesh: Solid-Nodes
          patch: interface
          write-data: [Displacements]
          read-data: [Forces]
        # - faces-mesh: Solid-Faces
          # patch: interface

precice-config-file: ../precice-config.xml